import type { Metadata } from 'next'
import React from "react";
import {ProviderRedux} from "@/redux/provider";
import {LayoutProvider} from "@/app/layoutProvider";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
    return (
      <html lang="en">
      <body>
      <ProviderRedux>
          <LayoutProvider>
              {children}
          </LayoutProvider>
      </ProviderRedux>
      </body>
      </html>
    )
}
